### ISSUE TITLE
Peer Review for David

### ISSUE THREAD

**Issue by HaoboRrrr** [HaoboRrrr/website_quarto_redux#4]
Hi David, 

This website has used unique color

Critical improvements needed
Nothing critical
Suggestions for improvement:
Maybe some personal information

Please consider adding/changing/removing:
personal information like program taking

Evaluation: 

I would give this website 100

Estimated mark:

100 out of 100.

Reason:

Successfuly pubish your website is a big accomplishment

**Comment by UTDQi** [comment]
Sorry, but you should write this in my section, not yours.
